### ISSUE TITLE
Scanner Does Not Always Create 16x16 chunk

### ISSUE THREAD

**Issue by Darkosto** [Eladkay/Scanner#1]
When placing the scanner next to another created chunk, this occurs: https://sx.artdude.uk/hotlink-ok/darkosto/CzyH-50423-1473740142.mp4

When creating a brand new chunk in the void, it generates 16x16. This only happens when next to another chunk generation.

**Comment by Eladkay** [comment]
Mmh. I'll try to fix it. Who knows, the fix I have in mind might even improve performance.

**Comment by Eladkay** [comment]
I actually have no idea how to fix it. If it can be left in, I'd suggest leaving it in for now.
