### ISSUE TITLE
Scanner 1.4 Crashes servers when a scanner is turned on.

### ISSUE THREAD

**Issue by Claycorp** [Eladkay/Scanner#10]
http://pastebin.com/PyLEqJZ7

**Comment by Eladkay** [comment]
Will take a look

**Comment by Eladkay** [comment]
Shouldn't happen. My guess is that you got a corrupted config. Try deleting it.

**Comment by Claycorp** [comment]
http://pastebin.com/nRM6h1gn - Deleted config
http://pastebin.com/ZKyN8irn - New Config

So you changed the config without telling anyone or putting in any checks??? Are you kidding me??? You do realise that everyone that downloaded skyfactory now has incorrect configs and when they use the mod it's going to crash...... Gesus....
EDIT: Hell Any modpack that uses the mod before V1.4 is going to have this issue...

**Comment by RogueLogix** [comment]
Corrupted != changed. A corrupted config is changed, but a changed config is not necessarily corrupted.

**Comment by Eladkay** [comment]
Don't think so. I didn't change the config lately. I'll check.

**Comment by Eladkay** [comment]
https://github.com/Eladkay/Scanner/blob/master/src/main/java/eladkay/scanner/Config.java
Last time I changed it was weeks before release

**Comment by Claycorp** [comment]
I just looked at all the change logs from Dec 10th till now and NONE of them say the configs changed. All of them are ~3-6 words that give practically no information to what changed at all. You MUST tell people that you changed configs. Most players don't even look at configs.... They install and play. Pack devs can't rewrite every config every version because they don't know if a config updated or not because that's a waste of time. Seriously, Use your head. Just a few days ago you didn't even know you had uploaded a new version 4 days before....

**Comment by Claycorp** [comment]
Even with a fresh config file the server still crashes.
http://pastebin.com/smtw5wcF Server crash time was 12PM on 1/26
File was last edited at 8AM 1/26 Plus the file was deleted 14 hours ago as you can see above.

**Comment by Eladkay** [comment]
Like I said. I didn't change the configs in ages. Please be patient and talk politely.
