### ISSUE TITLE
Scanner not replacing running water

### ISSUE THREAD

**Issue by ZeroKazuma** [Eladkay/Scanner#12]
Scanner isn't replacing running water blocks, see attached image
ModPack: SF 3.0.6
Version: 1.4

![image](https://cloud.githubusercontent.com/assets/13042341/22480869/e3cdd0ce-e7c0-11e6-8a5b-c8262db7ffae.png)

**Comment by Eladkay** [comment]
Hm, this is a consequence of a bug fix I did because people were complaining that lava is being replaced by blocks. I think I will reverse it.

**Comment by Eladkay** [comment]
https://minecraft.curseforge.com/projects/scanner/files/2378853
