### ISSUE TITLE
Game freezes while trying to connect to eladkay.pl

### ISSUE THREAD

**Issue by hgroene** [Eladkay/Scanner#13]
When playing offline my game is fine for about 10 seconds and then freezes for about 10 seconds in an endless cycle. The freeze starts when a DNS lookup of eladkay.pl starts and ends when NXDomain is received.

This is happening with scanner 1.4 minecraft 1.10.2 (Sky Factory 3)

**Comment by Eladkay** [comment]
Fixed in dev.

**Comment by Eladkay** [comment]
https://minecraft.curseforge.com/projects/scanner/files/2378853
