### ISSUE TITLE
SF3  Biome scanner crashes minecraft

### ISSUE THREAD

**Issue by shinderian** [Eladkay/Scanner#15]
Whenever I right click the biome scanner minecraft crashes.  I'm currently running SF3 3.0.8 with scanner 1.4.1.  It worked in 3.0.7 and the terrain scanner works properly.  The crash occurs on two different computers that I have minecraft on.
[Crash log](http://paste.feed-the-beast.com/view/647c4a1d)

**Comment by Eladkay** [comment]
@LatvianModder's fault it seems

**Comment by LatvianModder** [comment]
Update your mod, @Eladkay :P

**Comment by Eladkay** [comment]
To what? :P

**Comment by LatvianModder** [comment]
To latest/whateverIsInSF3 FTBLib

**Comment by Eladkay** [comment]
Will do I guess

**Comment by Deshtroyer** [comment]
Same/similar crash happening in SF 3.0.13 with scanner 1.5.1.
[crash-2017-07-24_05.45.46-client.txt](https://github.com/Eladkay/Scanner/files/1169567/crash-2017-07-24_05.45.46-client.txt)
No resource packs installed. Only modification to original modpack was an updated version of Draconic Evolution (to fix a crash with mob souls).

**Comment by Eladkay** [comment]
Did you update Scanner and FTBL to latest?

**Comment by Deshtroyer** [comment]
Ah, didn't notice scanner 1.5.2 was released. Just tested, it worked fine. Thanks for the immediate response, and sorry for wasting your time. :)

**Comment by Eladkay** [comment]
No problem
