### ISSUE TITLE
Biome Scanner crashing on right click

### ISSUE THREAD

**Issue by CraftSpider** [Eladkay/Scanner#16]
In a world with SkyFactory 3 + Project Red added on, when I try to use the Biome Scanner or the map feature on a Terrain Scanner, I crash with this log: [http://pastebin.com/raw/sBbDggV8](http://pastebin.com/raw/sBbDggV8).

**Comment by Eladkay** [comment]
Fixed in dev, waiting for textures to release.

**Comment by CraftSpider** [comment]
Alright thanks. Also just realized that link was just a circular reference sorry.
