### ISSUE TITLE
Callback is killing fps

### ISSUE THREAD

**Issue by fucnknown** [Eladkay/Scanner#17]
Modpack Skyfactory3, your mod is doing a callback and killing FPS, this error appears all over the whole log:

`[02:23:48] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://eladkay.pw/scanner/ScannerCallback.php?username=XXXXXXXXXX&timestamp=FriMar2402:23:47ART2017&version=1.4`

Upon mod removal, game returned to normal.

**Comment by sonicer105** [comment]
heh I just posted shortly after you about the same thing. Glad it's not just me.

**Comment by Eladkay** [comment]
oh, I didn't know it was that much of a problem, I was going to remove it anyways.
I'll push a build ASAP
