### ISSUE TITLE
1 FPS while mod is running (callback 403)

### ISSUE THREAD

**Issue by sonicer105** [Eladkay/Scanner#18]
I am getting 1 fps and get the following error every tick while any world is loaded:

> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://eladkay.pw/scanner/ScannerCallback.php?username=<PROFILE NAME>&timestamp=ThuMar2322:33:30PDT2017&version=1.4
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.GeneratedConstructorAccessor140.newInstance(Unknown Source)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.security.AccessController.doPrivileged(Native Method)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.security.AccessController.doPrivileged(Native Method)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at eladkay.scanner.proxy.ClientProxy.sendGet(ClientProxy.java:71)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at eladkay.scanner.proxy.ClientProxy.onClientTick(ClientProxy.java:57)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_683_ClientProxy_onClientTick_ClientTickEvent.invoke(.dynamic)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.lang.reflect.Method.invoke(Method.java:498)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.lang.reflect.Method.invoke(Method.java:498)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
> [22:33:30] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at org.multimc.EntryPoint.main(EntryPoint.java:53)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://eladkay.pw/scanner/ScannerCallback.php?username=<PROFILE NAME>&timestamp=ThuMar2322:33:30PDT2017&version=1.4
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.security.AccessController.doPrivileged(Native Method)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at eladkay.scanner.proxy.ClientProxy.sendGet(ClientProxy.java:70)
> [22:33:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 23 more`

Everything was fine yesterday, and this error started today. I changed nothing between now and then as far as i know.

I also went to the base URL mentioned in the error and it says your azure app is stopped, so that's a thing.

I'm using SkyFactory 3.0.6 with Scanner 1.4.

Full Log Here: https://paste.ee/p/4tWVh
Screenshot of F3 Here: https://imgur.com/a/LWFKN

If you need anything else, just ask.

**Comment by Eladkay** [comment]
oh, I didn't know it was that much of a problem, I was going to remove it anyways.
I'll push a build ASAP
