### ISSUE TITLE
Game Crash when opening Scanner

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Eladkay/Scanner#23]
[Report](https://pastebin.com/H3SX66t4)

don't really have to say anything more about it, the Report has all Info needed

**Comment by Eladkay** [comment]
UPDATE YOUR MOD.

**Comment by ProxyPlayerHD** [comment]
wait, i downloaded the newest Version from Curse. wtf
(using Curse Launcher to make the pack)
no need to scream at me... jeez mate

**Comment by Eladkay** [comment]
Oh, I see. 1.11 is currently unsupported.
You see this is a major major thing that you should have specified in your report because it’s easy to miss.
Will be fixed - never. I’ll port it to 1.12 once I’m satisfied with it.

**Comment by fungry04** [comment]
how do you update the mod? mines the same and i dont know how to update it, help appreciated.
