### ISSUE TITLE
Scanner mod crashing - how do you update it?

### ISSUE THREAD

**Issue by fungry04** [Eladkay/Scanner#25]
I have the scanner mod crashing problem and i know i need to upgrade it, but how? Is it an automatic thing? If someone could point me in the direction of a tutorial that would be great :)

**Comment by Eladkay** [comment]
I don't really know how to answer this I'm afraid. What sort of launcher/pack are you using? Twitch? Skyfactory?

**Comment by fungry04** [comment]
Twitch, I can see the update is there, and it shows I have the version underneath it installed. Not sure why I can't get the most recent update!

**Comment by fungry04** [comment]
Is there a way to force update Minecraft that you know off?

**Comment by Eladkay** [comment]
Not that I know of, I'm afraid

**Comment by fungry04** [comment]
I fixed it thanks! I downloaded the updated file and pasted it into the mobs file. Perfect 👍

**Comment by Eladkay** [comment]
Cool!
