### ISSUE TITLE
Terrain Scanner leaves starting block empty, causing a "hole" in the bottom bedrock layer

### ISSUE THREAD

**Issue by svj0hn** [Eladkay/Scanner#26]
This seems to happen whenever you generate a chunk directly via the Terrain Scanner. Flying below the bedrock, one will notice 1 block spaces in the bottom bedrock layer.

This does, however, not appear to occur if the chunk is pulled from the scanner queue instead of manually started.

**Comment by Eladkay** [comment]
Yeah

**Comment by Eladkay** [comment]
fixed in #33
