### ISSUE TITLE
1.12.2 version crashed while loading mods

### ISSUE THREAD

**Issue by WilliamBlaze** [Eladkay/Scanner#30]
The title says it all but here's the crash report for the exact details. 

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2019-03-26 12:57:23 EDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Scanner (scanner)
Caused by: java.lang.NoClassDefFoundError: eladkay/scanner/biome/TileEntityBiomeScanner
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.newInstance(Class.java:412)
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:166)
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:159)
    at eladkay.scanner.misc.NetworkHelper.init(NetworkHelper.java:19)
    at eladkay.scanner.ScannerMod.preInit(ScannerMod.java:80)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: eladkay.scanner.biome.TileEntityBiomeScanner
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 48 more
Caused by: java.lang.NoClassDefFoundError: eladkay/scanner/misc/BaseTE
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 50 more
Caused by: java.lang.ClassNotFoundException: eladkay.scanner.misc.BaseTE
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 54 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1510736472 bytes (1440 MB) / 2077753344 bytes (1981 MB) up to 5298978816 bytes (5053 MB)
  JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xincgc -Xmx5G -Xms2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2814 Optifine OptiFine_1.12.2_HD_U_E3 164 mods loaded, 164 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                   | Version                  | Source                                            | Signature                                |
       |:----- |:------------------------------------ |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                            | 1.12.2                   | minecraft.jar                                     | None                                     |
       | LCH   | mcp                                  | 9.42                     | minecraft.jar                                     | None                                     |
       | LCH   | FML                                  | 8.0.99.99                | forge-1.12.2-14.23.5.2814.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                                | 14.23.5.2814             | forge-1.12.2-14.23.5.2814.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | creativecoredummy                    | 1.0.0                    | minecraft.jar                                     | None                                     |
       | LCH   | itemphysic                           | 1.4.0                    | minecraft.jar                                     | None                                     |
       | LCH   | littletilescore                      | 1.0.0                    | minecraft.jar                                     | None                                     |
       | LCH   | bowinfinityfix                       | rv5                      | minecraft.jar                                     | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
       | LCH   | foamfixcore                          | 7.7.4                    | minecraft.jar                                     | None                                     |
       | LCH   | firstaidcore                         | 1.0.0                    | minecraft.jar                                     | None                                     |
       | LCH   | swordskillsapi                       | 1.1.0                    | 1.12.2-SwordSkillsApi-1.1.0.jar                   | None                                     |
       | LCH   | dynamicswordskills                   | 1.12.2-6.0.1             | 1.12.2-DynamicSwordSkills-6.0.1.jar               | None                                     |
       | LCH   | antiqueatlas                         | 4.4.9                    | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
       | LCH   | antiqueatlasoverlay                  | 1.2                      | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
       | LCH   | examplemod                           | 1.0                      | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
       | LCH   | astikorcarts                         | 1.12.2-0.1.2.6           | astikorcarts-1.12.2-0.1.2.6.jar                   | None                                     |
       | LCH   | backstab                             | 1.0.3.1                  | backstab-1.12.2-1.0.3.1.jar                       | None                                     |
       | LCH   | baublelicious                        | 1.4.0-4                  | Baublelicious-1.4.0-4.jar                         | None                                     |
       | LCH   | baubles                              | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
       | LCH   | baubleshulkerboxes                   | 4r                       | BaubleShulkerBoxes-1.12.2-4r.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | betteranimalsplus                    | 5.0.1                    | betteranimalsplus-5.0.1.jar                       | None                                     |
       | LCH   | betterbuilderswands                  | 0.13.1                   | BetterBuildersWands-1.12.2-0.13.1.269+13450ff.jar | None                                     |
       | LCH   | bettercombatmod                      | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                     | None                                     |
       | LCH   | forgelin                             | 1.8.2                    | Forgelin-1.8.2.jar                                | None                                     |
       | LCH   | betterfoliage                        | 2.2.0                    | BetterFoliage-MC1.12-2.2.0.jar                    | None                                     |
       | LCH   | hammercore                           | 2.0.4.2                  | HammerCore-1.12.2-2.0.4.2.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | biomepainttools                      | 1.1.4                    | BiomePaintTools-1.12.2-1.1.4.jar                  | None                                     |
       | LCH   | bookshelf                            | 2.3.577                  | Bookshelf-1.12.2-2.3.577.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | biomespecificdungeons                | 1.0.3                    | BiomeSpecificDungeons-1.12.2-1.0.3.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | bonsaitrees                          | 1.1.2                    | bonsaitrees-1.1.2-b144.jar                        | None                                     |
       | LCH   | thaumcraft                           | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
       | LCH   | thaumic_arcana                       | 1.2.0                    | Thaumic+Arcana-1.2.0.jar                          | None                                     |
       | LCH   | jei                                  | 4.15.0.270               | jei_1.12.2-4.15.0.270.jar                         | None                                     |
       | LCH   | botania                              | r1.10-360                | Botania+r1.10-360.jar                             | None                                     |
       | LCH   | botanianeedsit                       | 1.12.2-2.1-release       | botanianeedsit-1.12.2-2.1-release.jar             | None                                     |
       | LCH   | botanicbonsai                        | 0.0.0.botanicbonsai      | BotanicBonsai-1.0.0.5.jar                         | None                                     |
       | LCH   | bountiful                            | 2.2.0                    | Bountiful-2.2.0.jar                               | None                                     |
       | LCH   | carryon                              | 1.10                     | Carry+On+MC1.12.2+v1.10.jar                       | None                                     |
       | LCH   | cedendcake                           | 0.3                      | CedEndCake-1.12.2-0.3.jar                         | None                                     |
       | LCH   | chesthopper                          | 1.2.0                    | chesthopper-1.2.0.jar                             | None                                     |
       | LCH   | chesttransporter                     | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                 | None                                     |
       | LCH   | clarity                              | 1.1                      | clarity-1.1.jar                                   | None                                     |
       | LCH   | cleanview                            | 1.12.2-v1a               | CleanView-1.12.2-v1a.jar                          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | theoneprobe                          | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                       | None                                     |
       | LCH   | immersiveengineering                 | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCH   | clochecall                           | 1.1.1                    | ClocheCall-1.1.1.jar                              | None                                     |
       | LCH   | clumps                               | 3.1.1                    | Clumps-3.1.1.jar                                  | None                                     |
       | LCH   | comforts                             | 1.4.1.1                  | comforts-1.12.2-1.4.1.1.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCH   | containerfix                         | 1.0                      | ContainerFix+MC1.12.2+v1.0.jar                    | None                                     |
       | LCH   | controlling                          | 3.0.6                    | Controlling-3.0.6.jar                             | None                                     |
       | LCH   | cosmeticarmorreworked                | 1.12.2-v4                | CosmeticArmorReworked-1.12.2-v4.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4                | CosmeticArmorReworked-1.12.2-v4.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | craftingtweaks                       | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                   | None                                     |
       | LCH   | crafttweaker                         | 4.1.14                   | CraftTweaker2-1.12-4.1.14.jar                     | None                                     |
       | LCH   | ctgui                                | 1.0.0                    | CraftTweaker2-1.12-4.1.14.jar                     | None                                     |
       | LCH   | crafttweakerjei                      | 2.0.2                    | CraftTweaker2-1.12-4.1.14.jar                     | None                                     |
       | LCH   | creativecore                         | 1.9.9                    | CreativeCore_v1.9.41_mc1.12.2.jar                 | None                                     |
       | LCH   | customnpcs                           | 1.12                     | CustomNPCs_1.12.2(26aug18).jar                    | None                                     |
       | LCH   | customstartinggear                   | 1.2.0                    | CustomStartingGear-1.12-1.2.0.9-universal.jar     | None                                     |
       | LCH   | dailies                              | 1.12.2-6                 | dailies-1.12.2-6.jar                              | None                                     |
       | LCH   | deathquotes                          | 1.2.0                    | DeathQuotes-1.2.0-mc1.12-forge.jar                | None                                     |
       | LCH   | ding                                 | 1.0.1                    | Ding-1.12.1-1.0.1.jar                             | None                                     |
       | LCH   | dummycore                            | 2.4.112.5.               | DummyCoreUnofficial-2.4.112.5.jar                 | None                                     |
       | LCH   | dwarven_candles                      | 1.2                      | DwarvenCandles-[1.12]--1.2.jar                    | None                                     |
       | LCH   | dynamictrees                         | 1.12.2-0.9.4             | DynamicTrees-1.12.2-0.9.4.jar                     | None                                     |
       | LCH   | dynamictreestc                       | 1.12.2-1.4.1e            | DynamicTreesTC-1.12.2-1.4.1e.jar                  | None                                     |
       | LCH   | eplus                                | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | enchdesc                             | 1.1.8                    | EnchantmentDescriptions-1.12.2-1.1.8.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | endreborn                            | 0.3.0                    | EndReborn+II+[0.3.0].jar                          | None                                     |
       | LCH   | engineeredgolems                     | 1.0                      | Engineered+Golems-1.1.jar                         | None                                     |
       | LCH   | engineersdoors                       | 0.8.0                    | engineers_doors-1.12.2-0.8.0.jar                  | None                                     |
       | LCH   | enhancedarmaments                    | 1.3.15                   | EnhancedArmaments-1.3.15.jar                      | None                                     |
       | LCH   | mikesmodslib                         | 1.0.1                    | MikesModsLib-1.0.1.jar                            | None                                     |
       | LCH   | projecte                             | 1.12.2-PE1.4.0           | ProjectE-1.12.2-PE1.4.0.jar                       | None                                     |
       | LCH   | equivalentintegrations               | 0.3.0                    | EquivalentIntegrations-0.3.0.jar                  | None                                     |
       | LCH   | erosion                              | 2.2.1                    | Erosion-2.2.1.jar                                 | None                                     |
       | LCH   | exoticbirds                          | 1.0                      | Exotic+Birds+1.12.2-2.2.1.jar                     | None                                     |
       | LCH   | picklelib                            | 1.12.2-1.0.15.2          | picklelib-1.12.2-1.0.15.2.jar                     | None                                     |
       | LCH   | explosivefishing                     | 1.12.2-1.0.4.0           | explosivefishing-1.12.2-1.0.4.0.jar               | None                                     |
       | LCH   | extraalchemy                         | 0.3.8.6.1-release        | extraalchemy-0.3.8.6.1-release.jar                | None                                     |
       | LCH   | fasterladderclimbing                 | 0.1-146                  | FasterLadderClimbing-1.12-0.1-146.jar             | None                                     |
       | LCH   | fencejumper                          | 1.0.5                    | fencejumper-1.12-1.0.5.jar                        | None                                     |
       | LCH   | foamfix                              | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2.jar                         | None                                     |
       | LCH   | primal                               | 0.6.104                  | PrimalCore-1.12.2-0.6.104.jar                     | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
       | LCH   | forgecraft                           | 1.6.44                   | ForgeCraft-1.6.44.jar                             | None                                     |
       | LCH   | forgeendertech                       | 1.12.2-4.4.12.0          | ForgeEndertech-1.12.2-4.4.12.0-build.0273.jar     | None                                     |
       | LCH   | llibrary                             | 1.7.18                   | llibrary-1.7.18-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | fossil                               | 8.0.0                    | fossilsarcheology-8.0.0.jar                       | None                                     |
       | LCH   | friendlyfire                         | 1.5.8                    | FriendlyFire-1.12.2-1.5.8.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | ftblib                               | 5.4.1.93                 | FTBLib-5.4.1.93.jar                               | None                                     |
       | LCH   | ftbutilities                         | 5.4.0.88                 | FTBUtilities-5.4.0.88.jar                         | None                                     |
       | LCH   | grimoireofgaia                       | 1.6.9.3                  | GrimoireOfGaia3-1.12.2-1.6.9.3.jar                | None                                     |
       | LCH   | hopperducts                          | 1.5                      | hopperducts-mc1.12-1.5.jar                        | None                                     |
       | LCH   | horsetweaks                          | 1.0.4                    | HorseTweaks_1.12.2-1.0.4.jar                      | None                                     |
       | LCH   | thaumadditions                       | 12r                      | ThaumicAdditions-1.12.2-12r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | iceandfire                           | 1.7.0                    | iceandfire-1.7.0-1.12.2.jar                       | None                                     |
       | LCH   | improvedmobs                         | 1.4.0                    | ImprovedMobs-1.12.2-1.4.0.jar                     | None                                     |
       | LCH   | instantunify                         | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                     | None                                     |
       | LCH   | inventorytweaks                      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | ironchest                            | 1.12.2-7.0.45.830        | ironchest-1.12.2-7.0.45.830.jar                   | None                                     |
       | LCH   | keepinginventory                     | 2.4                      | KeepingInventory-1.12.2-2.4.jar                   | None                                     |
       | LCH   | keywizard                            | 1.12.2-1.5.3-b1          | keywizard-1.12.2-1.5.3-b1.jar                     | None                                     |
       | LCH   | satako                               | 2.23                     | Satako+1.12-2.23.jar                              | None                                     |
       | LCH   | killer_table                         | 0.7                      | Killer+table-1.12.2-0.7.jar                       | None                                     |
       | LCH   | littletiles                          | 1.5.0                    | LittleTiles_v1.5.0-pre130_mc1.12.2.jar            | None                                     |
       | LCH   | maxpotidext                          | 0.0.2.1                  | maxpotidext-0.0.2.1.jar                           | None                                     |
       | LCH   | radixcore                            | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar              | None                                     |
       | LCH   | mca                                  | 1.12.2-5.3.1             | MCA-1.12.x-5.3.1-universal.jar                    | None                                     |
       | LCH   | millenaire                           | Millénaire 7.1.3         | millenaire-7.1.3.jar                              | None                                     |
       | LCH   | minetraps                            | 1.0.3                    | MineTraps-1.12.2-(v.1.0.3).jar                    | None                                     |
       | LCH   | nanfix                               | Final                    | nanfix-final-absorbtion.jar                       | None                                     |
       | LCH   | naturalnetherportals                 | 1.2.0                    | naturalnetherportals-1.2.0-mc1.12.x.jar           | None                                     |
       | LCH   | naturescompass                       | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                   | None                                     |
       | LCH   | netherportalfix                      | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar                 | None                                     |
       | LCH   | nopoisonregen                        | 1.0                      | NMPR-1.0.jar                                      | None                                     |
       | LCH   | yurtmod                              | 9.0.7                    | NomadicTents[1.12.2]-9.0.7.jar                    | None                                     |
       | LCH   | nmsot                                | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar           | None                                     |
       | LCH   | recipehandler                        | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar             | None                                     |
       | LCH   | neid                                 | 1.5.4.3                  | NotEnoughIDs-1.5.4.3.jar                          | None                                     |
       | LCH   | oops                                 | @VERSION@                | oops-1.12-5.11.jar                                | None                                     |
       | LCH   | oreexcavation                        | 1.4.137                  | OreExcavation-1.4.137.jar                         | None                                     |
       | LCH   | passthroughsigns                     | 2.1.5                    | PassthroughSigns-1.12.2-2.1.5.jar                 | None                                     |
       | LCH   | patchouli                            | 1.0-18                   | Patchouli-1.0-18.jar                              | None                                     |
       | LCH   | petbat                               | 1.4.8                    | PetBat-1.12.2.jar                                 | None                                     |
       | LCH   | quickleafdecay                       | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                 | None                                     |
       | LCH   | recycler                             | 3.0.0                    | recycler-3.0.0-1.12.jar                           | None                                     |
       | LCH   | sandro                               | 1.2d                     | Redstone+++ver1.2d.jar                            | None                                     |
       | LCH   | redstoneplusplus                     | 1.2d                     | Redstone+++ver1.2d.jar                            | None                                     |
       | LCH   | redstonepaste                        | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                    | None                                     |
       | LCH   | resize                               | 1.10                     | Resizing+Potion-r1.10.jar                         | None                                     |
       | LCH   | silentlib                            | 3.0.13                   | SilentLib-1.12.2-3.0.13+167.jar                   | None                                     |
       | LCH   | scalinghealth                        | 1.3.33                   | ScalingHealth-1.12.2-1.3.33+135.jar               | None                                     |
       | LCE   | scanner                              | 1.6.2                    | scanner-1.6.2.jar                                 | None                                     |
       | LC    | sharpbone                            | 1.0                      | SharpBone-1.12.2-1.0.jar                          | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
       | LC    | somanyenchantments                   | 0.4.0                    | SoManyEnchantments+0.4.0+Preview.jar              | None                                     |
       | LC    | stg                                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                              | None                                     |
       | LC    | teleportingxp                        | 1.1.1.1                  | teleportingxp-1.1.1.1.jar                         | None                                     |
       | LC    | tenshilib                            | 1.1.0                    | TenshiLib-1.12.2-1.1.0.jar                        | None                                     |
       | LC    | thaumic_calculator                   | 0.4                      | Thaumic+Calculations-1.12.2-0.4.jar               | None                                     |
       | LC    | thaumicbases                         | 3.3.310.5r               | thaumicbases-3.3.345.6r.jar                       | None                                     |
       | LC    | thaumicbrewing                       | 1.0.2                    | thaumicbrewing-1.0.2.jar                          | None                                     |
       | LC    | thaumicequivalence                   | 1.12.2-1.0.5             | ThaumicEquivalence-1.12.2-1.0.5.jar               | None                                     |
       | LC    | tcinventoryscan                      | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar        | None                                     |
       | LC    | thaumicperiphery                     | 0.3.0                    | thaumicperiphery-0.3.0.jar                        | None                                     |
       | LC    | thaumicrestoration                   | 1.3.1                    | ThaumicRestoration-1.3.1.jar                      | None                                     |
       | LC    | topaddons                            | 1.12.2-1.10.1            | topaddons-1.12.2-1.10.1.jar                       | None                                     |
       | LC    | trashslot                            | 8.4.6                    | TrashSlot_1.12.1-8.4.6.jar                        | None                                     |
       | LC    | tumbleweed                           | 1.11-0.4.5               | tumbleweed-1.11-0.4.5.jar                         | None                                     |
       | LC    | universalbestiary                    | 1.1.0                    | universalbestiary-1.12.2-1.1.0.jar                | None                                     |
       | LC    | unloader                             | 1.2.0                    | unloader-1.2.0.jar                                | None                                     |
       | LC    | upsizer                              | 4.0.1                    | upsizer-mc1.12-4.0.1.jar                          | None                                     |
       | LC    | vanillafix                           | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LC    | variedcommodities                    | 1.12.2                   | VariedCommodities_1.12.2(15may18.jar              | None                                     |
       | LC    | villagenames                         | 2.0                      | VillageNames-1.12.2-2.0.jar                       | None                                     |
       | LC    | villagermarket                       | 1.0.1                    | villager-market-1.12.2-1.0.1.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | visuals                              | 6r                       | Visuals-1.12.2-6r.jar                             | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LC    | wanionlib                            | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                          | None                                     |
       | LC    | waterstrainer                        | 3.2.0                    | WaterStrainer-1.12-3.2.0.jar                      | None                                     |
       | LC    | waystones                            | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                       | None                                     |
       | LC    | xpfromharvest                        | 1.0                      | xpfromharvest-1.12-1.0.1.jar                      | None                                     |
       | LC    | firstaid                             | 1.6.3                    | firstaid-1.6.3.jar                                | 7904c4e13947c8a616c5f39b26bdeba796500722 |
       | LC    | adfinders                            | 1.12.2-2.3.5.0           | AdFinders-1.12.2-2.3.5.0-build.0274.jar           | None                                     |
       | LC    | peckish                              | 1.1.0                    | Peckish-1.12-1.1.0.jar                            | None                                     |
       | LC    | unidict                              | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                          | None                                     |
  Loaded coremods (and transformers): LittlePatchingLoader (LittleTiles_v1.5.0-pre130_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      TenshiCore (TenshiLib-1.12.2-1.1.0.jar)
                                        com.flemmli97.tenshilib.asm.ASMTransformer
                                      BedPatch (bedpatch-2.2-1.12.2.jar)
                                        com.mordenkainen.bedpatch.BedPatchASM
                                      Plugin (NotEnoughIDs-1.5.4.3.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      CreativePatchingLoader (CreativeCore_v1.9.41_mc1.12.2.jar)
                                        
                                      DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
                                        DummyCore.ASM.DCASMManager
                                      FirstAid CoreMod (firstaid-core-1.6.3.jar)
                                        ichttt.mods.firstaid.common.asm.PotionTransformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.19_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
                                        com.github.parker8283.bif.Transformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LoadingPlugin (AdFinders-1.12.2-2.3.5.0-build.0274.jar)
                                        com.endertech.minecraft.mods.adfinders.finder.Render
                                      CorePlugin (ForgeEndertech-1.12.2-4.4.12.0-build.0273.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      HCASM (HammerCore-1.12.2-2.0.4.2.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      Max Potion ID Extender (maxpotidext-0.0.2.1.jar)
                                        zabi.minecraft.maxpotidext.MPIDTransformer
                                      Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
                                        com.chocohead.biab.BornInABarn
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer

**Comment by IGCBOOM** [comment]
Ah, whoops, apparently I forgot to put COFH Redstone Flux as a dependency, go add [CoFH RedstoneFlux](https://minecraft.curseforge.com/projects/redstone-flux/files) and it should fix it.

**Comment by IGCBOOM** [comment]
@Eladkay can close this now, the issue was resolved.
