### ISSUE TITLE
JEI/multiple terrain scanner crash

### ISSUE THREAD

**Issue by redgoblin88** [Eladkay/Scanner#31]
i have had 4 terrain scanners building at a time but when i look at any of their interfaces i get a JEI crash
note that i was forced to update forge from my previous 2811 version of forge as enderio was constantly crashing and required a more later version.

(as shown in the screenshot the 4 scanners building the superflat bedrock world)

here is the crashlog: https://pastebin.com/UAi6tECs

forge: 14.23.5.2824
scanner: 1.6.3
jei: 15.0.272

![2019-03-30_13 08 34](https://user-images.githubusercontent.com/13396472/55276582-5f3beb80-52ed-11e9-86e3-50474e493c06.png)

**Comment by IGCBOOM** [comment]
I don't think forge is the issue. So this only happens when you have 4 scanners running at the same time, not 2, 3, or 5?

**Comment by IGCBOOM** [comment]
Also, does opening a Scanner Queue cause a crash?

**Comment by redgoblin88** [comment]
im not sure if multiple causes the problem or not, and yes opening the scanner crashes

**Comment by IGCBOOM** [comment]
Ok, if opening a scanner queue crashes, I might know the issue. One final thing just to make sure, does opening a Biome Scanner (Any of them) crash?

**Comment by redgoblin88** [comment]
yep, from the crashlog it seems its when jei tries to render inside the gui it crashes

**Comment by IGCBOOM** [comment]
Well, that’s specifically the terrain scanner GUI. What about the GUI for the scanner queue or the biome scanner?

**Comment by redgoblin88** [comment]
im not too sure sorry, ive dissabled the mod for now and launching the pack does take a little bit :/

**Comment by IGCBOOM** [comment]
Is the specific pack on Curseforge? Because then I might be able to work with it better.

**Comment by redgoblin88** [comment]
its not, im making it in the twitch launcher sorry

**Comment by IGCBOOM** [comment]
Maybe someone else knows, I can't seem to replicate the issue.

**Comment by IGCBOOM** [comment]
Maybe @Eladkay knows the issue, it seems to be a complication between JEI rendering and the Terrain Scanner Gui rendering.

**Comment by Eladkay** [comment]
Check your JEI integration @igcboom if there’s nothing there this might be a JEI bug

**Comment by Eladkay** [comment]
Closed in 1538dbe.
