### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BizzBolt5** [Eladkay/Scanner#35]
When I try to start up minecraft with this mod, midway through loading all my mods, it crashes the game. If you can fix it, it would be appreciated

**Comment by BizzBolt5** [comment]
Wait, I just realized that I hadn't downloaded all the dependencies. My apologies

**Comment by Eladkay** [comment]
I was going to forgive you, but even if you did have all of the dependencies, I'd have had no way of debugging the crash as you didn't provide a crash log. Please do pay attention to that for the next bug report you submit, to my mods or to any other mods.
