### ISSUE TITLE
Minecraft Crashes

### ISSUE THREAD

**Issue by BraveCaperCat** [Eladkay/Scanner#46]
**Exit Code -1
Crash Log:
Included File
Mod List:**

	| State | ID                         | Version       | Source                                        | Signature                                |
	|:----- |:-------------------------- |:------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2        | minecraft.jar                                 | None                                     |
	| LCH   | mcp                        | 9.42          | minecraft.jar                                 | None                                     |
	| LCH   | FML                        | 8.0.99.99     | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                      | 14.23.5.2854  | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | quarryplus                 | 12.5.1        | AdditionalEnchantedMiner-1.12.2-12.5.1.jar    | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCH   | quarryplus_ct              | 12.5.1        | AdditionalEnchantedMiner-1.12.2-12.5.1.jar    | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCH   | jei                        | 4.16.1.301    | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCH   | quark                      | r1.6-179      | Quark-r1.6-179.jar                            | None                                     |
	| LCH   | autoreglib                 | 1.3-32        | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCH   | biomesoplenty              | 7.0.1.2444    | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCH   | clumps                     | 3.1.2         | Clumps-3.1.2.jar                              | None                                     |
	| LCH   | crafttweaker               | 4.1.20        | CraftTweaker2-1.12-4.1.20.652.jar             | None                                     |
	| LCH   | ctgui                      | 1.0.0         | CraftTweaker2-1.12-4.1.20.652.jar             | None                                     |
	| LCH   | crafttweakerjei            | 2.0.3         | CraftTweaker2-1.12-4.1.20.652.jar             | None                                     |
	| LCH   | defaultworldgenerator-port | 1.12-2.3      | DefaultWorldGenerator-port-1.12-2.3.jar       | None                                     |
	| LCH   | journeymap                 | 1.12.2-5.7.1  | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCH   | jeresources                | 0.9.2.60      | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
	| LCH   | mantle                     | 1.12-1.3.3.55 | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCH   | flexiblemarker             | 1.8           | Marker-1.8-universal.jar                      | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCH   | mcjtylib_ng                | 3.5.4         | mcjtylib-1.12-3.5.4.jar                       | None                                     |
	| LCH   | refinedstorage             | 1.6.16        | refinedstorage-1.6.16.jar                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | rftools                    | 7.73          | rftools-1.12-7.73.jar                         | None                                     |
	| LCH   | rftoolsdim                 | 5.71          | rftoolsdim-1.12-5.71.jar                      | None                                     |
	| LCE   | scanner                    | 1.6.12        | scanner-1.6.12.jar                            | None                                     
**[latest.log](https://github.com/Eladkay/Scanner/files/7803622/latest.log)
[crash-2022-01-03_18.51.47-client.txt](https://github.com/Eladkay/Scanner/files/7803625/crash-2022-01-03_18.51.47-client.txt)**

I Use Windows 11 But It Says Windows 10 For Some Weird Reason

**Comment by BraveCaperCat** [comment]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Scanner (scanner)

**Comment by BraveCaperCat** [comment]
I Have Not Played This Minecraft Installation In At Least 3 Months Ago I Think, **Also I Think The Idea Is Great**

**Comment by IGCBOOM** [comment]
> **The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Scanner (scanner)**

You do seem to be missing some of the required dependencies listed on the CF page description, try installing them and see if it works.

**Comment by BraveCaperCat** [comment]
It Works Now, Thanks @IGCBOOM For Helping Me With This One!
